name: tidal

on:
  schedule:
    - cron: '0 5 * * 5'
  workflow_dispatch:
    inputs:
      env_vars:
        description: 'space-separated env vars, e.g. "DEBUG=1"'
        required: false
        default: ''
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - env:
          T_CI: ${{ secrets.T_CI }}
          T_CS: ${{ secrets.T_CS }}
          T_RT: ${{ secrets.T_RT }}
          T_PI_ALBUMS: ${{ secrets.T_PI_ALBUMS }}
          T_PI_EPS: ${{ secrets.T_PI_EPS }}
          T_PI_SINGLES: ${{ secrets.T_PI_SINGLES }}
          PYTHONUNBUFFERED: 1
        run: ${{ inputs.env_vars }} DATE=$(date -d "last saturday" +%Y-%m-%d) ./tidal.py
